# Run tests over snakefile workflow
---
name: Tests

on:  # yamllint disable-line rule:truthy
  push:
    branches: [main, devel]
  pull_request:
    branches: [main, devel]

jobs:

  Pre-Commit:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          lfs: 'true'
      - name: Run pre-commit on all files
        uses: pre-commit/action@v3.0.0
        with:
          extra_args: --all-files

  Testing:
    runs-on: ubuntu-latest
    needs:
      - Pre-Commit
    steps:
      - uses: actions/checkout@v3
        with:
          lfs: 'true'

      - name: Cache
        uses: actions/cache@v3
        with:
          path: |
            .snakemake/conda
            ~/.cache/pre-commit/
          key: snakemake-conda

      - name: Download environments
        uses: snakemake/snakemake-github-action@v1.24.0
        with:
          directory: .
          snakefile: workflow/Snakefile
          args: >
            --conda-cleanup-pkgs cache
            --conda-create-envs-only
            --conda-frontend mamba
            --cores 3
            --use-conda

      - name: Clean conda cache
        run: conda clean --all --yes

      - name: Preprocess
        uses: snakemake/snakemake-github-action@v1.24.0
        with:
          directory: .
          snakefile: workflow/Snakefile
          args: >
            preprocess
            --conda-cleanup-pkgs cache
            --conda-frontend mamba
            --cores 3
            --latency-wait 5
            --show-failed-logs
            --use-conda


      - name: Quantify
        uses: snakemake/snakemake-github-action@v1.24.0
        with:
          directory: .
          snakefile: workflow/Snakefile
          args: >
            quantify
            --conda-cleanup-pkgs cache
            --conda-frontend mamba
            --cores 3
            --latency-wait 5
            --show-failed-logs
            --use-conda


      - name: Report
        uses: snakemake/snakemake-github-action@v1.24.0
        with:
          directory: .
          snakefile: workflow/Snakefile
          args: >
            report
            --conda-cleanup-pkgs cache
            --conda-frontend mamba
            --cores 3
            --latency-wait 5
            --show-failed-logs
            --use-conda

      - name: Delete everything
        run: |
          sudo find results -not -name "*.log" -type f -delete -print

      - uses: actions/upload-artifact@v3
        if: failure()
        with:
          name: results
          path: |
            results/**/*.log
